# Generated by Django 4.1.1 on 2022-09-14 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('episode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mexico'), (2, 'Japan'), (3, 'United States'), (4, 'other')], null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index.person')),
                ('nickname', models.CharField(blank=True, max_length=20)),
            ],
            bases=('index.person',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='index.person')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
            bases=('index.person',),
        ),
        migrations.CreateModel(
            name='Post_Postlabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.post')),
                ('post_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.post_label')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.post_category'),
        ),
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.ManyToManyField(blank=True, through='index.Post_Postlabel', to='index.post_label'),
        ),
        migrations.CreateModel(
            name='Anime_Animelabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anime')),
                ('anime_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anime_label')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.anime_genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='label',
            field=models.ManyToManyField(blank=True, through='index.Anime_Animelabel', to='index.anime_label'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.user'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.post')),
                ('user', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to='index.user')),
            ],
        ),
        migrations.CreateModel(
            name='Calification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anime')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.artist')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='artist',
            field=models.ManyToManyField(blank=True, through='index.Anime_Artist', to='index.artist'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.PositiveSmallIntegerField(choices=[(1, 'want to watch'), (2, 'watching'), (3, 'temporary stopped'), (4, 'left')])),
                ('episodes_watched', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user')),
            ],
        ),
    ]
